services:
  - type: web
    name: futbol-formaciones-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
    plan: free
    autoDeploy: true
